@echo off
REM Install /spec + /build (Gate 1, Gate 1.5) into a project's .claude\ directory.
REM
REM Usage (run inside the target project, or pass a path as %1):
REM   curl -fsSL -o "%TEMP%\spec-install.cmd" https://raw.githubusercontent.com/suifei/spec/main/scripts/install.cmd && call "%TEMP%\spec-install.cmd" && del "%TEMP%\spec-install.cmd"
REM
REM Only touches: <target>\.claude\skills\spec\, <target>\.claude\skills\build\,
REM <target>\.claude\commands\spec.md, <target>\.claude\commands\build.md.
REM Never touches CLAUDE.md, SPEC.md, or .spec\ — those are the target project's own
REM and are generated by /spec itself on first run.
setlocal

set "REPO=suifei/spec"
set "BRANCH=main"
if "%~1"=="" (set "TARGET=%CD%") else (set "TARGET=%~1")

echo == Installing /spec + /build into: %TARGET% ==

set "TMP=%TEMP%\spec-install-%RANDOM%%RANDOM%"
mkdir "%TMP%" >nul 2>nul

REM Prefer git (most reliable through proxies/redirects); fall back to curl+tar.
where git >nul 2>nul && git clone --depth 1 --branch %BRANCH% "https://github.com/%REPO%.git" "%TMP%\src" >nul 2>nul

if not exist "%TMP%\src\.claude\skills\spec" (
  where curl >nul 2>nul || goto :missing_tools
  where tar  >nul 2>nul || goto :missing_tools

  if exist "%TMP%\src" rmdir /S /Q "%TMP%\src"
  mkdir "%TMP%\src"
  curl -fsSL "https://github.com/%REPO%/archive/refs/heads/%BRANCH%.tar.gz" -o "%TMP%\src.tar.gz" || goto :fetch_failed
  tar -xzf "%TMP%\src.tar.gz" -C "%TMP%\src" --strip-components=1 || goto :fetch_failed
)

if not exist "%TMP%\src\.claude\skills\spec" (
  echo ERROR: fetched source is missing .claude\skills\spec — aborting. 1>&2
  rmdir /S /Q "%TMP%" >nul 2>nul
  exit /b 1
)

if not exist "%TARGET%\.claude\skills" mkdir "%TARGET%\.claude\skills"
if not exist "%TARGET%\.claude\commands" mkdir "%TARGET%\.claude\commands"
if exist "%TARGET%\.claude\skills\spec" rmdir /S /Q "%TARGET%\.claude\skills\spec"
if exist "%TARGET%\.claude\skills\build" rmdir /S /Q "%TARGET%\.claude\skills\build"

xcopy /E /I /Y "%TMP%\src\.claude\skills\spec" "%TARGET%\.claude\skills\spec" >nul
xcopy /E /I /Y "%TMP%\src\.claude\skills\build" "%TARGET%\.claude\skills\build" >nul
copy /Y "%TMP%\src\.claude\commands\spec.md" "%TARGET%\.claude\commands\spec.md" >nul
copy /Y "%TMP%\src\.claude\commands\build.md" "%TARGET%\.claude\commands\build.md" >nul

rmdir /S /Q "%TMP%" >nul 2>nul

echo Installed:
echo   %TARGET%\.claude\skills\spec\
echo   %TARGET%\.claude\skills\build\
echo   %TARGET%\.claude\commands\spec.md
echo   %TARGET%\.claude\commands\build.md
echo.
echo Next: open Claude Code in %TARGET% and run  /spec  to start.
endlocal
goto :eof

:missing_tools
echo ERROR: need either 'git', or 'curl' + 'tar', on PATH. 1>&2
rmdir /S /Q "%TMP%" >nul 2>nul
endlocal
exit /b 1

:fetch_failed
echo ERROR: failed to download or extract the repository archive. 1>&2
rmdir /S /Q "%TMP%" >nul 2>nul
endlocal
exit /b 1
