#!/usr/bin/env bash
# Install /spec + /build + /yolo (Gate 1, Gate 1.5, and the autonomous loop)
# into a project's .claude/ directory.
#
# Usage (run inside the target project, or pass a path):
#   curl -fsSL https://raw.githubusercontent.com/suifei/spec/main/scripts/install.sh | bash
#   curl -fsSL https://raw.githubusercontent.com/suifei/spec/main/scripts/install.sh | bash -s -- /path/to/project
#
# Only touches those runtime paths plus <target>/.claude/spec-install.manifest.
# Never touches CLAUDE.md, SPEC.md, or .spec/ — those are the target project's own
# and are generated by /spec itself on first run.
set -euo pipefail

REPO="suifei/spec"
BRANCH="main"
TARGET="${1:-$PWD}"

echo "== Installing /spec + /build + /yolo into: $TARGET =="

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

fetch_with_git() {
  command -v git >/dev/null 2>&1 || return 1
  git clone --depth 1 --branch "$BRANCH" "https://github.com/$REPO.git" "$TMP/src" >/dev/null 2>&1
}

fetch_with_tar() {
  command -v curl >/dev/null 2>&1 || return 1
  command -v tar  >/dev/null 2>&1 || return 1
  curl -fsSL "https://github.com/$REPO/archive/refs/heads/$BRANCH.tar.gz" -o "$TMP/src.tar.gz"
  mkdir -p "$TMP/src"
  tar -xzf "$TMP/src.tar.gz" -C "$TMP/src" --strip-components=1
}

sha256_file() {
  if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | awk '{print $1}'
  else sha256sum "$1" | awk '{print $1}'; fi
}

if [ -n "${SPEC_INSTALL_SOURCE:-}" ]; then
  cp -R "$SPEC_INSTALL_SOURCE" "$TMP/src"
elif fetch_with_git; then
  :
elif fetch_with_tar; then
  :
else
  echo "ERROR: need either 'git', or 'curl' + 'tar', on PATH." >&2
  exit 1
fi

SRC="$TMP/src"
[ -d "$SRC/.claude/skills/spec" ] || {
  echo "ERROR: fetched source is missing .claude/skills/spec — aborting." >&2
  exit 1
}

bash "$SRC/scripts/verify-distribution.sh" "$SRC" "$SRC/scripts/distributable-files.txt"

REVISION="$(git -C "$SRC" rev-parse HEAD 2>/dev/null || printf '%s' "$BRANCH")"
STAGE="$TMP/stage"
BACKUP="$TMP/backup"
mkdir -p "$STAGE" "$BACKUP/skills" "$BACKUP/commands"
while IFS='|' read -r role path; do
  [ "$role" = runtime ] || continue
  mkdir -p "$STAGE/$(dirname "$path")"
  cp "$SRC/$path" "$STAGE/$path"
done < "$SRC/scripts/distributable-files.txt"

for name in spec build yolo; do [ -f "$STAGE/.claude/skills/$name/SKILL.md" ] || { echo "ERROR: staged $name skill incomplete" >&2; exit 1; }; done

mkdir -p "$TARGET/.claude/skills" "$TARGET/.claude/commands"
installed=0
swapping=0
rollback() {
  [ "$installed" -eq 1 ] && return
  [ "$swapping" -eq 1 ] || return
  for name in spec build yolo; do
    rm -rf "$TARGET/.claude/skills/$name"; [ ! -e "$BACKUP/skills/$name" ] || mv "$BACKUP/skills/$name" "$TARGET/.claude/skills/$name"
    rm -f "$TARGET/.claude/commands/$name.md"; [ ! -e "$BACKUP/commands/$name.md" ] || mv "$BACKUP/commands/$name.md" "$TARGET/.claude/commands/$name.md"
  done
  rm -f "$TARGET/.claude/spec-install.manifest"
  [ ! -f "$BACKUP/spec-install.manifest" ] || mv "$BACKUP/spec-install.manifest" "$TARGET/.claude/spec-install.manifest"
}
trap 'rollback; rm -rf "$TMP"' EXIT
[ ! -f "$TARGET/.claude/spec-install.manifest" ] || cp "$TARGET/.claude/spec-install.manifest" "$BACKUP/spec-install.manifest"
for name in spec build yolo; do [ ! -e "$TARGET/.claude/skills/$name" ] || cp -R "$TARGET/.claude/skills/$name" "$BACKUP/skills/$name"; done
for name in spec build yolo; do [ ! -e "$TARGET/.claude/commands/$name.md" ] || cp "$TARGET/.claude/commands/$name.md" "$BACKUP/commands/$name.md"; done
swapping=1
rm -rf "$TARGET/.claude/skills/spec" "$TARGET/.claude/skills/build" "$TARGET/.claude/skills/yolo"
rm -f "$TARGET/.claude/commands/spec.md" "$TARGET/.claude/commands/build.md" "$TARGET/.claude/commands/yolo.md" "$TARGET/.claude/spec-install.manifest"
[ "${SPEC_INSTALL_FAIL_AFTER_BACKUP:-0}" != 1 ] || { echo "ERROR: injected post-backup failure" >&2; exit 73; }
for name in spec build yolo; do mv "$STAGE/.claude/skills/$name" "$TARGET/.claude/skills/$name"; done
for name in spec build yolo; do mv "$STAGE/.claude/commands/$name.md" "$TARGET/.claude/commands/$name.md"; done
printf 'revision=%s\nsource=%s@%s\nmanifest_sha256=%s\n' "$REVISION" "$REPO" "$BRANCH" "$(sha256_file "$SRC/scripts/distributable-files.txt")" > "$TARGET/.claude/spec-install.manifest"
installed=1

echo "Installed:"
echo "  $TARGET/.claude/skills/spec/"
echo "  $TARGET/.claude/skills/build/"
echo "  $TARGET/.claude/skills/yolo/"
echo "  $TARGET/.claude/commands/spec.md"
echo "  $TARGET/.claude/commands/build.md"
echo "  $TARGET/.claude/commands/yolo.md"
echo "  revision: $REVISION"
echo
echo "Next: open Claude Code in $TARGET and run  /spec  to start."
