#requires -Version 5.1
<#
Install /spec + /build (Gate 1, Gate 1.5) into a project's .claude\ directory.

Usage (run inside the target project, from ANY shell -- cmd.exe, PowerShell, a
Run dialog -- this invokes powershell.exe explicitly):
  powershell -NoProfile -ExecutionPolicy Bypass -Command "irm https://raw.githubusercontent.com/suifei/spec/main/scripts/install.ps1 | iex"

Or, if you're already inside a PowerShell prompt:
  irm https://raw.githubusercontent.com/suifei/spec/main/scripts/install.ps1 | iex

To install into a different directory, download first then run with -Target:
  iwr -UseBasicParsing https://raw.githubusercontent.com/suifei/spec/main/scripts/install.ps1 -OutFile install.ps1
  .\install.ps1 -Target C:\path\to\project

Only touches: <Target>\.claude\skills\spec\, <Target>\.claude\skills\build\,
<Target>\.claude\commands\spec.md, <Target>\.claude\commands\build.md.
Never touches CLAUDE.md, SPEC.md, or .spec\ -- those are the target project's own
and are generated by /spec itself on first run.
#>
param(
    [string]$Target = (Get-Location).Path,
    [string]$Repo = 'suifei/spec',
    [string]$Branch = 'main'
)

Write-Host "== Installing /spec + /build into: $Target =="

$tmp = Join-Path ([System.IO.Path]::GetTempPath()) ('spec-install-' + [System.Guid]::NewGuid().ToString('N').Substring(0, 8))
New-Item -ItemType Directory -Path $tmp -Force | Out-Null

try {
    $src = Join-Path $tmp 'src'
    $gotSrc = $false

    # Prefer git (most reliable through proxies/redirects). *> redirects ALL native
    # output streams to $null without going through PowerShell's error-handling
    # machinery, so git's normal clone progress on stderr can't be mistaken for a
    # terminating error.
    if (Get-Command git -ErrorAction SilentlyContinue) {
        git clone --depth 1 --branch $Branch "https://github.com/$Repo.git" "$src" *> $null
        if (Test-Path (Join-Path $src '.claude\skills\spec')) { $gotSrc = $true }
    }

    # Fall back to a pure-PowerShell path: no git, no curl, no tar required --
    # Invoke-WebRequest + Expand-Archive are built into PowerShell 5.1+.
    if (-not $gotSrc) {
        $zipPath = Join-Path $tmp 'src.zip'
        $zipUrl = "https://github.com/$Repo/archive/refs/heads/$Branch.zip"
        Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath -UseBasicParsing -ErrorAction Stop
        $extractDir = Join-Path $tmp 'extract'
        Expand-Archive -Path $zipPath -DestinationPath $extractDir -Force -ErrorAction Stop
        $inner = Get-ChildItem -Path $extractDir -Directory | Select-Object -First 1
        if ($null -eq $inner) { throw 'Could not find the extracted repository folder.' }
        $src = $inner.FullName
        if (Test-Path (Join-Path $src '.claude\skills\spec')) { $gotSrc = $true }
    }

    if (-not $gotSrc) {
        throw 'Fetched source is missing .claude\skills\spec -- aborting. Need either git, or working internet access to github.com.'
    }

    $skillsDir = Join-Path $Target '.claude\skills'
    $commandsDir = Join-Path $Target '.claude\commands'
    New-Item -ItemType Directory -Path $skillsDir -Force | Out-Null
    New-Item -ItemType Directory -Path $commandsDir -Force | Out-Null

    foreach ($name in @('spec', 'build')) {
        $dst = Join-Path $skillsDir $name
        if (Test-Path $dst) { Remove-Item $dst -Recurse -Force }
        Copy-Item (Join-Path $src ".claude\skills\$name") $dst -Recurse -Force -ErrorAction Stop
    }
    Copy-Item (Join-Path $src '.claude\commands\spec.md')  (Join-Path $commandsDir 'spec.md')  -Force -ErrorAction Stop
    Copy-Item (Join-Path $src '.claude\commands\build.md') (Join-Path $commandsDir 'build.md') -Force -ErrorAction Stop

    Write-Host 'Installed:'
    Write-Host "  $skillsDir\spec\"
    Write-Host "  $skillsDir\build\"
    Write-Host "  $commandsDir\spec.md"
    Write-Host "  $commandsDir\build.md"
    Write-Host ''
    Write-Host "Next: open Claude Code in $Target and run  /spec  to start."
}
finally {
    Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue
}
