#!/usr/bin/env bash
# Install /spec + /build + /yolo (Gate 1, Gate 1.5, and the autonomous loop)
# into a project's .claude/ directory.
#
# Usage (run inside the target project, or pass a path):
#   curl -fsSL https://raw.githubusercontent.com/suifei/spec/main/scripts/install.sh | bash
#   curl -fsSL https://raw.githubusercontent.com/suifei/spec/main/scripts/install.sh | bash -s -- /path/to/project
#
# Only touches: <target>/.claude/skills/{spec,build,yolo}/ and
# <target>/.claude/commands/{spec,build,yolo}.md.
# Never touches CLAUDE.md, SPEC.md, or .spec/ — those are the target project's own
# and are generated by /spec itself on first run.
set -euo pipefail

REPO="suifei/spec"
BRANCH="main"
TARGET="${1:-$PWD}"

echo "== Installing /spec + /build + /yolo into: $TARGET =="

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

fetch_with_git() {
  command -v git >/dev/null 2>&1 || return 1
  git clone --depth 1 --branch "$BRANCH" "https://github.com/$REPO.git" "$TMP/src" >/dev/null 2>&1
}

fetch_with_tar() {
  command -v curl >/dev/null 2>&1 || return 1
  command -v tar  >/dev/null 2>&1 || return 1
  curl -fsSL "https://github.com/$REPO/archive/refs/heads/$BRANCH.tar.gz" -o "$TMP/src.tar.gz"
  mkdir -p "$TMP/src"
  tar -xzf "$TMP/src.tar.gz" -C "$TMP/src" --strip-components=1
}

if fetch_with_git; then
  :
elif fetch_with_tar; then
  :
else
  echo "ERROR: need either 'git', or 'curl' + 'tar', on PATH." >&2
  exit 1
fi

SRC="$TMP/src"
[ -d "$SRC/.claude/skills/spec" ] || {
  echo "ERROR: fetched source is missing .claude/skills/spec — aborting." >&2
  exit 1
}

mkdir -p "$TARGET/.claude/skills" "$TARGET/.claude/commands"
rm -rf "$TARGET/.claude/skills/spec" "$TARGET/.claude/skills/build" "$TARGET/.claude/skills/yolo"
cp -R "$SRC/.claude/skills/spec"       "$TARGET/.claude/skills/spec"
cp -R "$SRC/.claude/skills/build"      "$TARGET/.claude/skills/build"
cp -R "$SRC/.claude/skills/yolo"       "$TARGET/.claude/skills/yolo"
cp    "$SRC/.claude/commands/spec.md"  "$TARGET/.claude/commands/spec.md"
cp    "$SRC/.claude/commands/build.md" "$TARGET/.claude/commands/build.md"
cp    "$SRC/.claude/commands/yolo.md"  "$TARGET/.claude/commands/yolo.md"

echo "Installed:"
echo "  $TARGET/.claude/skills/spec/"
echo "  $TARGET/.claude/skills/build/"
echo "  $TARGET/.claude/skills/yolo/"
echo "  $TARGET/.claude/commands/spec.md"
echo "  $TARGET/.claude/commands/build.md"
echo "  $TARGET/.claude/commands/yolo.md"
echo
echo "Next: open Claude Code in $TARGET and run  /spec  to start."
