#requires -Version 5.1
<#
Install /spec + /build + /yolo (Gate 1, Gate 1.5, and the autonomous loop) into a
project's .claude\ directory.

Usage (run inside the target project, from ANY shell -- cmd.exe, PowerShell, a
Run dialog -- this invokes powershell.exe explicitly):
  powershell -NoProfile -ExecutionPolicy Bypass -Command "irm https://raw.githubusercontent.com/suifei/spec/main/scripts/install.ps1 | iex"

Or, if you're already inside a PowerShell prompt:
  irm https://raw.githubusercontent.com/suifei/spec/main/scripts/install.ps1 | iex

To install into a different directory, download first then run with -Target:
  iwr -UseBasicParsing https://raw.githubusercontent.com/suifei/spec/main/scripts/install.ps1 -OutFile install.ps1
  .\install.ps1 -Target C:\path\to\project

Only touches those runtime paths plus <Target>\.claude\spec-install.manifest.
Never touches CLAUDE.md, SPEC.md, or .spec\ -- those are the target project's own
and are generated by /spec itself on first run.
#>
param(
    [string]$Target = (Get-Location).Path,
    [string]$Repo = 'suifei/spec',
    [string]$Branch = 'main',
    [string]$Source = ''
)

Write-Host "== Installing /spec + /build + /yolo into: $Target =="

$tmp = Join-Path ([System.IO.Path]::GetTempPath()) ('spec-install-' + [System.Guid]::NewGuid().ToString('N').Substring(0, 8))
New-Item -ItemType Directory -Path $tmp -Force | Out-Null

try {
    $src = Join-Path $tmp 'src'
    $gotSrc = $false

    if ($Source) {
        Copy-Item $Source $src -Recurse -Force -ErrorAction Stop
        $gotSrc = Test-Path (Join-Path $src '.claude\skills\spec')
    }

    # Prefer git (most reliable through proxies/redirects). *> redirects ALL native
    # output streams to $null without going through PowerShell's error-handling
    # machinery, so git's normal clone progress on stderr can't be mistaken for a
    # terminating error.
    if (-not $gotSrc -and (Get-Command git -ErrorAction SilentlyContinue)) {
        git clone --depth 1 --branch $Branch "https://github.com/$Repo.git" "$src" *> $null
        if (Test-Path (Join-Path $src '.claude\skills\spec')) { $gotSrc = $true }
    }

    # Fall back to a pure-PowerShell path: no git, no curl, no tar required --
    # Invoke-WebRequest + Expand-Archive are built into PowerShell 5.1+.
    if (-not $gotSrc) {
        $zipPath = Join-Path $tmp 'src.zip'
        $zipUrl = "https://github.com/$Repo/archive/refs/heads/$Branch.zip"
        Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath -UseBasicParsing -ErrorAction Stop
        $extractDir = Join-Path $tmp 'extract'
        Expand-Archive -Path $zipPath -DestinationPath $extractDir -Force -ErrorAction Stop
        $inner = Get-ChildItem -Path $extractDir -Directory | Select-Object -First 1
        if ($null -eq $inner) { throw 'Could not find the extracted repository folder.' }
        $src = $inner.FullName
        if (Test-Path (Join-Path $src '.claude\skills\spec')) { $gotSrc = $true }
    }

    $distributionManifest = Join-Path $src 'scripts\distributable-files.txt'
    if (-not (Test-Path $distributionManifest)) { throw 'Distribution manifest missing.' }
    foreach ($entry in Get-Content $distributionManifest) {
        if ([string]::IsNullOrWhiteSpace($entry)) { continue }
        $parts = $entry.Split('|', 2); if ($parts.Count -ne 2 -or $parts[0] -notin @('runtime', 'support')) { throw "Invalid manifest entry: $entry" }
        $relative = $parts[1]
        if ($relative.Contains('..') -or [System.IO.Path]::IsPathRooted($relative)) { throw "Unsafe distribution path: $relative" }
        if (-not (Test-Path (Join-Path $src $relative))) { throw "Distribution incomplete; missing: $relative" }
    }

    if (-not $gotSrc) {
        throw 'Fetched source is missing .claude\skills\spec -- aborting. Need either git, or working internet access to github.com.'
    }

    $skillsDir = Join-Path $Target '.claude\skills'
    $commandsDir = Join-Path $Target '.claude\commands'
    New-Item -ItemType Directory -Path $skillsDir -Force | Out-Null
    New-Item -ItemType Directory -Path $commandsDir -Force | Out-Null

    $stage = Join-Path $tmp 'stage'
    $backup = Join-Path $tmp 'backup'
    New-Item -ItemType Directory -Path $stage, (Join-Path $backup 'skills'), (Join-Path $backup 'commands') -Force | Out-Null
    foreach ($entry in Get-Content $distributionManifest) {
        $parts = $entry.Split('|', 2); if ($parts[0] -ne 'runtime') { continue }
        $relative = $parts[1]; $stagedFile = Join-Path $stage $relative
        New-Item -ItemType Directory -Path (Split-Path $stagedFile -Parent) -Force | Out-Null
        Copy-Item (Join-Path $src $relative) $stagedFile -Force -ErrorAction Stop
    }
    foreach ($name in @('spec', 'build', 'yolo')) {
        if (-not (Test-Path (Join-Path $stage ".claude\skills\$name\SKILL.md"))) { throw "Staged $name skill incomplete." }
    }

    $installed = $false
    $swapping = $false
    try {
        $installRecord = Join-Path $Target '.claude\spec-install.manifest'
        if (Test-Path $installRecord) { Copy-Item $installRecord (Join-Path $backup 'spec-install.manifest') -Force }
        foreach ($name in @('spec', 'build', 'yolo')) {
            $dst = Join-Path $skillsDir $name; if (Test-Path $dst) { Copy-Item $dst (Join-Path $backup "skills\$name") -Recurse -Force -ErrorAction Stop }
            $cmd = Join-Path $commandsDir "$name.md"; if (Test-Path $cmd) { Copy-Item $cmd (Join-Path $backup "commands\$name.md") -Force -ErrorAction Stop }
        }
        $swapping = $true
        foreach ($name in @('spec', 'build', 'yolo')) {
            $dst = Join-Path $skillsDir $name; if (Test-Path $dst) { Remove-Item $dst -Recurse -Force }
            $cmd = Join-Path $commandsDir "$name.md"; if (Test-Path $cmd) { Remove-Item $cmd -Force }
        }
        if (Test-Path $installRecord) { Remove-Item $installRecord -Force }
        foreach ($name in @('spec', 'build', 'yolo')) {
            Move-Item (Join-Path $stage ".claude\skills\$name") (Join-Path $skillsDir $name) -Force -ErrorAction Stop
            Move-Item (Join-Path $stage ".claude\commands\$name.md") (Join-Path $commandsDir "$name.md") -Force -ErrorAction Stop
        }
        if (Get-Command git -ErrorAction SilentlyContinue) { $revision = (& git -C $src rev-parse HEAD 2>$null) }
        if (-not $revision) { $revision = $Branch }
        $manifestHash = (Get-FileHash $distributionManifest -Algorithm SHA256).Hash.ToLowerInvariant()
        "revision=$revision`nsource=$Repo@$Branch`nmanifest_sha256=$manifestHash" | Set-Content $installRecord -Encoding ASCII -ErrorAction Stop
        $installed = $true
    }
    finally {
        if (-not $installed -and $swapping) {
            foreach ($name in @('spec', 'build', 'yolo')) {
                $dst = Join-Path $skillsDir $name; if (Test-Path $dst) { Remove-Item $dst -Recurse -Force }
                $old = Join-Path $backup "skills\$name"; if (Test-Path $old) { Move-Item $old $dst -Force }
                $cmd = Join-Path $commandsDir "$name.md"; if (Test-Path $cmd) { Remove-Item $cmd -Force }
                $oldCmd = Join-Path $backup "commands\$name.md"; if (Test-Path $oldCmd) { Move-Item $oldCmd $cmd -Force }
            }
            $installRecord = Join-Path $Target '.claude\spec-install.manifest'; if (Test-Path $installRecord) { Remove-Item $installRecord -Force }
            $oldRecord = Join-Path $backup 'spec-install.manifest'; if (Test-Path $oldRecord) { Move-Item $oldRecord $installRecord -Force }
        }
    }

    Write-Host 'Installed:'
    Write-Host "  $skillsDir\spec\"
    Write-Host "  $skillsDir\build\"
    Write-Host "  $skillsDir\yolo\"
    Write-Host "  $commandsDir\spec.md"
    Write-Host "  $commandsDir\build.md"
    Write-Host "  $commandsDir\yolo.md"
    Write-Host ''
    Write-Host "Next: open Claude Code in $Target and run  /spec  to start."
}
finally {
    Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue
}
